// <auto-generated />
using System;
using JobTypeMgt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobTypeMgt.Migrations
{
    [DbContext(typeof(JobTypeMgtContext))]
    [Migration("20231210160539_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JobTypeMgt.models.JobTypeDet", b =>
                {
                    b.Property<int>("JobTypeDetPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobTypeDetPk"), 1L, 1);

                    b.Property<string>("JobTypStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTypeMilestone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobTypePk")
                        .HasColumnType("int");

                    b.HasKey("JobTypeDetPk");

                    b.HasIndex("JobTypePk");

                    b.ToTable("JobTypeDet", (string)null);
                });

            modelBuilder.Entity("JobTypeMgt.models.JobTypeHed", b =>
                {
                    b.Property<int>("JobTypePk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobTypePk"), 1L, 1);

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddMach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AddUser")
                        .HasColumnType("int");

                    b.Property<string>("JobTypActive")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JobTypPrefix")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("JobTypeDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("JobTypecode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("Session")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("timestamp_column")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("JobTypePk");

                    b.ToTable("JobTypeHed", (string)null);
                });

            modelBuilder.Entity("JobTypeMgt.models.JobTypeDet", b =>
                {
                    b.HasOne("JobTypeMgt.models.JobTypeHed", "JobTypeHed")
                        .WithMany()
                        .HasForeignKey("JobTypePk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobTypeHed");
                });
#pragma warning restore 612, 618
        }
    }
}
